name    'dwhatmuff-clamav'
version '0.1.0'
source 'github.com/danielwhatmuff/dwhatmuff-clamav'
author 'dwhatmuff'
license 'Apache License, Version 2.0'
summary 'dwhatmuff-clamav'
description 'Module to manage ClamAV'
project_page 'github.com/danielwhatmuff/dwhatmuff-clamav'

dependency 'puppetlabs/stdlib', '>= 4.6.0'
